- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars/vars.yml
  vars_prompt:
    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
  tasks:
    - name: Create User and Set Password
      ansible.builtin.­user:
        name: "{{ user }}"
        password: "{{ user_password }}"
        home: "/home/{{ user }}"
        shell: /bin/bash
